apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World!"
    - name: hello-next
      image: alpine
      command:
        - echo
      args:
        - "Hello Next World on alpine!"