apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: gitlab-push-events-trigger
      interceptors:
        - name: "verify-gitlab-payload"
          ref:
            name: "gitlab"
            kind: ClusterInterceptor
          params:
            - name: secretRef
              value:
                secretName: "gitlab-secret"
                secretKey: "secretToken"
            - name: eventTypes
              value:
                - "Push Hook"
        - name: "split-ref-heads-from-branch-name"
          ref:
            name: cel
          params:
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.ref.split('/')[2]"
      bindings:
        - name: gitrevision
          value: $(body.checkout_sha)
        - name: gitbranch
          value: $(extensions.branch_name)
        - name: gitrepositoryurl
          value: $(body.repository.git_http_url)
        - name: gitrepository_pathonly
          value: $(body.project.path_with_namespace)
        - name: project_name
          value: $(body.project.name)
      template:
        spec:
          params:
            - name: gitrevision
            - name: gitbranch
            - name: gitrepositoryurl
            - name: gitrepository_pathonly
            - name: project_name
            - name: message
              description: The message to print
              default: This is the default message
            - name: contenttype
              description: The Content-Type of the event
          resourcetemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: buildpacks-test-pipeline-run-
              spec:
                serviceAccountName: buildpacks-service-account-gitlab
                pipelineRef:
                  name: buildpacks-test-pipeline
                workspaces:
                  - name: source-workspace
                    subPath: source
                    persistentVolumeClaim:
                      claimName: buildpacks-source-pvc
                  - name: cache-workspace
                    subPath: cache
                    persistentVolumeClaim:
                      claimName: buildpacks-source-pvc
                  - name: maven-repo-cache
                    subPath: maven-repo-cache
                    persistentVolumeClaim:
                      claimName: buildpacks-source-pvc
                  - name: config-workspace
                    subPath: config
                    persistentVolumeClaim:
                      claimName: buildpacks-source-pvc
                params:
                  - name: IMAGE
                    value: "registry.gitlab.com/$(tt.params.gitrepository_pathonly)" #here our GitLab's registry url must be configured
                  - name: SOURCE_URL
                    value: $(tt.params.gitrepositoryurl)
                  - name: REPO_PATH_ONLY
                    value: $(tt.params.gitrepository_pathonly)
                  - name: PROJECT_NAME
                    value: $(tt.params.project_name)
                  - name: SOURCE_REVISION
                    value: $(tt.params.gitrevision)
                  - name: SOURCE_BRANCH
                    value: $(tt.params.gitbranch)
                  - name: CONFIG_URL
                    value: "http://gitlab.com/$(tt.params.gitrepository_pathonly)-config.git"
                  - name: CONFIG_REVISION
                    value: argocd